config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  root 'posts#index'
  get 'home/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    #before_filter :configure_permitted_parameters, if: :devise_controller?

protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) << :name
        devise_parameter_sanitizer.for(:account_update) << :name
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order("created_at DESC").paginate(
      :page => params[:page], :per_page => 12)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:description, :image, :name)
    end
end

def correct_user
  @post = current_user.posts.find_by(id: params[:id])
  redirect_to posts_path, notice: "Not authorized to edis this post" if @post.nil?
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Lemos</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Home", root_path %></li>
        <li class=""><%= link_to "About us", home_about_path %></li>       
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class=""><%= link_to 'Edit', edit_user_registration_path %>   </li>
          <li class=""><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
          <li class=""><%= link_to 'Posts', posts_path %></li>
          <li class=""><%= link_to 'New Post', new_post_path %></li>
        <% else %>
          <li class=""><%= link_to 'Sign up', new_user_registration_path %></li>
          <li class=""><%= link_to 'Sign in', new_user_session_path %></li>
        <% end %>
      </ul>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->

  
</nav>

app/views/home/_jumbotron.html.erb
<div class='container'>
    <div class="jumbotron center">
        <h1>Hello yall</h1>
        <p>I'm soo guud at dis</p>
        <% if user_signed_in? %>
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-lg' %>
        <% else %>
            <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
            <%= link_to 'Sign in', new_user_session_path, class: 'btn btn-default btn-lg' %>
        
        <% end %>
    </div>
</div>

app/views/home/_jumbs.html.erb
<!DOCTYPE_html>

<head>

</head>

<body>
    <%= render 'home/jumbotron' unless user_signed_in? %>
</body>

</html>

app/views/home/about.html.erb
<!DOCTYPE_html>

<head></head>

<body>
<h1>Home#about</h1>

</body>

</html>

app/views/home/index.html.erb
<!DOCTYPE_html>

<head>

</head>

<body>
    <%= render 'home/jumbotron' %>
</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Eduardo Lemos Portfolio</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
         
</head>


<body>
  
  <%= render 'home/header' %>
  <!--For each instance of a flash, shows the respective alert message-->
  <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class:"alert alert-info") %>
  <% end %>
  


  <div class="container">
    <%= yield %>
  </div>

</body>

</html>

app/views/posts/_form.html.erb
<div class="panel-body">
  <%= form_for @post, html: {multipart:true} do |form| %>
    <% if post.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% post.errors.full_messages.each do |message| %>
            <li>
              <%= message %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form">
      <%= form.label :description %>
      <%= form.text_field :description, class:'form-control'%>
    </div>

    <div class="form">
      <%= form.label :image %>
      <%= form.file_field :image, class:"form-control" %>
    </div>

    <div class="actions">
      <%= form.submit 'Submit', class:'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= render 'home/jumbs' unless user_signed_in? %>

<div id= "posts" class= "transitions-enabled">
  <% @posts.each do |post| %>
    <div class="box">
      <div class="panel panel-default">
        <%= link_to image_tag(post.image.url(:thumb)), post %> <br/>
          <div class="panel-body">
            <%= post.description %> <br/>
            <%= post.user.name %> </br>
          </div>
          <% if post.user == current_user %> 
            <div class= "panel-footer">
              <%= link_to 'Edit', edit_post_path(post), class: "btn btn-default" %>
              <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
            </div>
          <% end %> 
      </div>
    </div>
    <br/><br/>  
  <% end %>

</div>
<div class="center">
  <%= will_paginate @posts, renderer: BootstrapPagination::Rails  %>
</div>

app/views/posts/new.html.erb
<div class="panel panel-default">
    <div class="panel-header">
        <h1>New Post</h1>
    </div>

    <%= render 'form', post: @post %>
        
    <div class="panel-footer">
        <%= link_to 'Back', posts_path %>
    </div>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>



<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center">
        <%= image_tag @post.image.url(:medium) %><br/>
      </div>
      <div class="panel-body">
        <%= @post.description %>
        <br/>
        <%= @post.user.name%>
      </div>
      <div class="panel-footer">
        <% if @post.user == current_user %>
          <%= link_to 'Edit', edit_post_path(@post) %> |
        <% end %>
        <%= link_to 'Back', posts_path %>
      </div>
    </div>
  </div>
</div>